load("@buildifier_prebuilt//:rules.bzl", "buildifier")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//:tools/clang_format/clang_format.bzl", "clang_format")

buildifier(
    name = "buildifier.check",
    exclude_patterns = [
        "./.git/*",
        "./bazel-*",
        "./build/*",
        "./third_party/*",
    ],
    lint_mode = "warn",
    mode = "diff",
)

buildifier(
    name = "buildifier.fix",
    exclude_patterns = [
        "./.git/*",
        "./bazel-*",
        "./build/*",
        "./third_party/*",
    ],
    lint_mode = "fix",
    mode = "fix",
)

clang_format(
    name = "clang-format",
    directories = ["gfx"],
    extensions = [
        ".cpp",
        ".hpp",
        ".c",
        ".h",
        ".cu",
        ".cuh",
    ],
    mode = "check",
)

cc_binary(
    name = "gamepad-demo",
    srcs = ["gfx/applications/gamepad_demo_main.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "//gfx/graphics:window",
        "//gfx/input:gamepad",
    ],
)

cc_binary(
    name = "demo-texture-compute",
    srcs = [
        "gfx/applications/texture_compute_main.cpp",
    ],
    copts = ["-std=c++20"],
    deps = [
        "//gfx/compute:components",
        "//gfx/graphics:components",
        "//gfx/graphics:window",
        "//gfx/shaders:texture",
        "//gfx/utils:arg_parser",
        "//gfx/vocabulary",
    ],
)

cc_library(
    name = "demo",
    srcs = ["gfx/applications/demo_application.cpp"],
    hdrs = [
        "gfx/applications/demo_application.hpp",
        "//gfx/utils:timestamp.hpp",
    ],
    copts = ["-std=c++20"],
    strip_include_prefix = "/gfx",
    deps = [
        "//gfx/compute:components",
        "//gfx/compute:dump",
        "//gfx/graphics:components",
        "//gfx/graphics:dump",
        "//gfx/graphics:window",
        "//gfx/shaders:texture",
    ],
)

cc_binary(
    name = "demo-app",
    srcs = [
        "gfx/applications/demo_application_main.cpp",
    ],
    copts = ["-std=c++20"],
    deps = [
        ":demo",
        "@fmt",
    ],
)
