bazel_dep(name = "rules_cuda", version = "0.3.0")

cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")
cuda.toolkit(
    name = "cuda",
    toolkit_path = "",
)
use_repo(cuda, "cuda")

bazel_dep(name = "catch2", version = "3.11.0")
bazel_dep(name = "bazel_skylib", version = "1.7.0")
bazel_dep(name = "rules_cc", version = "0.2.16")
bazel_dep(name = "stb", version = "0.0.0-20251026-f1c79c0")
bazel_dep(name = "glew", version = "2.2.0")
bazel_dep(name = "glfw", version = "3.4.0.bcr.1")
bazel_dep(name = "fmt", version = "12.1.0")
bazel_dep(name = "glm", version = "1.0.3")
bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.2")
bazel_dep(name = "rules_vulkan", version = "0.7.0")

vulkan_sdk = use_extension("@rules_vulkan//vulkan:extensions.bzl", "vulkan_sdk")
vulkan_sdk.toolchain(version = "1.4.313")
use_repo(vulkan_sdk, "vulkan_sdk_1.4.313")

register_toolchains("@vulkan_sdk_1.4.313//:all")
